language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
    - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - cmake
      - cmake-data
      - libglew-dev
      - libfreetype6
      - libdevil-dev