language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
    - mkdir sdl2install
    - export SDL2DIR="`pwd`/sdl2install"
    - wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
    - tar xzf SDL2-2.0.3.tar.gz
    - cd SDL2-2.0.3
    - ./configure --prefix=$SDL2DIR
    - make
    - make install
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - cmake
      - cmake-data
      - libglew-dev
      - libfreetype6
      - libdevil-dev
      - libsdl2-dev

