language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
      - zoogie/sdl2-snapshots
    packages:
      - gcc-4.7
      - g++-4.7
      - cmake
      - cmake-data
      - libglew-dev
      - libfreetype6
      - libdevil-dev
      - libsdl2-dev

